[package]
name = "numerical"
version = "0.1.0"
edition = "2021"
description = "Algorithm for numerical analysis"
license = "MIT"
authors = ["UnrealInReal <liuxiaonanbj@163.com>"]

[dependencies]
log = "0.4"

[dev-dependencies]
env_logger = "0.10"